#!@bash@/bin/bash
set -euo pipefail
me=$(@coreutils@/bin/basename "${BASH_SOURCE[0]}")
here=$(@coreutils@/bin/dirname "${BASH_SOURCE[0]}")

cleanup() {
    if [ -v tmp ]; then @coreutils@/bin/rm -rf "$tmp"; fi
}
unset -v tmp
trap cleanup EXIT
tmp=$(@coreutils@/bin/mktemp --tmpdir --directory "$me".XXXXXXXX)

tmpsubdir() {
    @coreutils@/bin/rm -rf "$tmp/$1"
    @coreutils@/bin/mkdir "$tmp/$1"
}

for f in "$@"; do
    tmpsubdir items
    @xml2@/bin/xml2 < "$f" |
    "$here"/xml2-pieces /feed/entry "$tmp"/items/xx
    for g in "$itemsdir"/*; do
        tmpsubdir links
        "$here"/xml2-pieces link "$g" "$tmp"/links/xx
        for h in "$tmp"/links/*; do
            @awk@/bin/awk '
                BEGIN { a["rel"] = "alternate" }
                /^@/ {
                    i = index($0, "@")
                    j = index($0, "=")
                    a[substr($0, i+1, j-i-1)] = substr($0, j+1)
                }
                END {
                    if (a["rel"] == "alternate" && "href" in a)
                        print "properlink=" a["href"]
                }
                ' "$h"
        done >>"$g"
        @awk@/bin/awk -f "$here"/../lib/items.awk --source '
            $1 == "title" { stash("title") }
            $1 == "properlink" { stash("link") }
            $1 == "id" { stash("id") }
            $1 == "updated" { stash("date") }
            $1 == "amfdr:item-name" { stash("reddit-item-name") }
            $1 == "amfdr:subreddit" { stash("subreddit") }
            $1 == "amfdr:self" { stash("reddit-self") }
            ' "$g"
    done
done
