#!@bash@/bin/bash
set -euo pipefail
me=$(@coreutils@/bin/basename "${BASH_SOURCE[0]}")
here=$(@coreutils@/bin/dirname "${BASH_SOURCE[0]}")

XSD_DATE_FMT="%FT%T.%N%:z"

cleanup() {
    if [ -v tmp ]; then @coreutils@/bin/rm -rf "$tmp"; fi
}
unset -v tmp
trap cleanup EXIT
tmp=$(@coreutils@/bin/mktemp --tmpdir --directory "$me".XXXXXXXX)

for f in "$@"; do
    @xml2@/bin/xml2 < "$f" |
    "$here"/xml2-pieces /rss/channel/item "$tmp"/xx
    for f in "$tmp"/xx*; do
        @coreutils@/bin/cat "$f" |
        while IFS='=' read k v; do
            case "$k" in
                pubDate) v=$(@coreutils@/bin/date +"${XSD_DATE_FMT}" --date="$v") ;;
                *) ;;
            esac
            echo "$k=$v"
        done |
        @awk@/bin/awk -f "$here"/../lib/items.awk --source '
            $1 == "title" { stash("title") }
            $1 == "link" { stash("link") }
            $1 == "guid" { stash("id") }
            $1 == "pubDate" { stash("date") }
            '
    done
done
