#!@bash@/bin/bash
set -euo pipefail
me=$(@coreutils@/bin/basename "${BASH_SOURCE[0]}")

FDFD_DATA=tag:amotlpaa.org,2016:fdfd-data/
XS=http://www.w3.org/2001/XMLSchema#
DC=http://purl.org/dc/terms/

rdf() {
    @redland@/bin/rdfproc -s sqlite "$datadir"/db "$@"
}

command_new() {
    if [ $# -ne 0 ]; then exit_usage "new"; fi
    local now
    now=$(@coreutils@/bin/date -Is)
    @coreutils@/bin/mkdir -p "$datadir"
    rdf --new add-typed \
        "$FDFD_DATA"db \
        "$DC"created \
        "$now" \
        "" \
        "$XS"dateTime \
        "$FDFD_DATA"db
}

exit_usage() {
    local msg
    case $# in
        0) msg="COMMAND [ARG ...]" ;;
        *) msg="$@" ;;
    esac
    echo "usage: $me DATADIR $msg" >&2
    exit 1
}

if [ $# -lt 2 ]; then exit_usage; fi
datadir=$1
command=$2
shift 2
"command_$command" "$@"
