#!@bash@/bin/bash
set -euo pipefail
me=$(@coreutils@/bin/basename "${BASH_SOURCE[0]}")
here=$(@coreutils@/bin/dirname "${BASH_SOURCE[0]}")

DEFAULT_RATE=5

if [ $# -ne 2 ]; then
    echo "usage: $me DBDIR RATEFILE" >&2
    exit 2
fi
dbdir=$1
ratefile=$2
s3base=$(@coreutils@/bin/cat "$dbdir"/s3base)

cleanup() {
    if [ -v tmp ]; then rm -rf "$tmp"; fi
}
trap cleanup EXIT
tmp=$(@coreutils@/bin/mktemp --tmpdir --directory "$me".XXXXXXXX)

{
    "$here"/fdfd fetchable "$dbdir" | @sed@/bin/sed 's,^,fetch ,'
    "$here"/fdfd explorable "$dbdir" | @sed@/bin/sed 's,^,explore ,'
} >"$tmp"/actionable

# rate control to smooth out spikes in number of actions
avail=$(@coreutils@/bin/wc -l <"$tmp"/actionable)
if [ -e "$ratefile" ]; then
    oldrate=$(@coreutils@/bin/cat "$ratefile")
else
    oldrate=$DEFAULT_RATE
fi
if [ "$avail" -gt 0 ]; then
    newrate=$(@coreutils@/bin/echo "0.99*$oldrate + 0.01*$avail" |
        @bc@/bin/bc -l)
    echo "$newrate" >"$ratefile"
else
    newrate=$oldrate
fi
todo=$(echo "$newrate" |@awk@/bin/awk '{ print int($0+0.5) }')

@coreutils@/bin/sort -R "$tmp"/actionable |
@sed@/bin/sed -n "1,${todo}p" |
while read verb url; do
  if ! "$here"/fdfd "$verb" "$s3base" "$url" | "$here"/fdfd merge "$dbdir"; then
    echo "$me: error doing: $verb $url" >&2
  fi
done
