#!@bash@/bin/bash
set -euo pipefail
me=$(@coreutils@/bin/basename "${BASH_SOURCE[0]}")

case $# in
    2)  path=$1
        file=-
        prefix=$2
        ;;
    3)  path=$1
        file=$2
        prefix=$3
        ;;
    *)  echo "usage: $me /foo/bar [file] prefix" >&2
        exit 2
        ;;
esac
pathregex=${path//\//\\/}

@coreutils@/bin/csplit \
    --prefix "$prefix" \
    "$file" \
    "/^${pathregex}$/" '{*}' \
    >/dev/null
for f in "$prefix"*; do
    @sed@/bin/sed -i \
        -e "/^${pathregex}\//!d" \
        -e "s,^${pathregex}\/,," \
        "$f"
done
